### PR TITLE
Apply fix from bug #9

### PR DESCRIPTION
**Pull request by colinnewell**
This is simply the application of the patch from the bug report.

### CODE REVIEW

**Comment by holcapek** [comment]
@petdance With this change applied to #11 , `./Build authortest` do pass and Travis is happy. I'd also be happy seeing this PR being merged.
@colinnewell Thanks!

**Comment by petdance** [comment]
OK, I'll see what I can do tomorrow.

**Comment by holcapek** [comment]
@petdance Hi, is there a chance for this being merged anytime soon? I would like to re-open #11 with this change applied. Thanks!
@colinnewell Could you please enable Travis CI for this PR in order to make it _visible_ the test no longer fails? Thanks!

**Comment by colinnewell** [comment]
@holcapek I don't understand?  I can see a green tick by the commit and the Travis results there.  The travis wasn't run by the forked repo, but it has since the pull request has been made.

**Comment by holcapek** [comment]
@colinnewell I am terribly sorry. I failed to click on _Show all checks_. I am just used to seeing it without doing anything.

**Pull request merged**
